const lang = {
    'en':{
        'button_download': 'Download',
        'enable': false,
        'name': 'English'
    },
    'jp':{
        'enable': false,
        'name': '日本語'
    },
    'tw':{
        'enable': false,
        'name': 'Tâi-gí'
    },
    'zh':{
        'button_download': '下載',
        'document_title': 'SVG QR code 產生器',
        'enable': true,
        'error_content_too_long': '文字內容過長',
        'field_bg': '背景',
        'field_fg': '前景',
        'field_info': '資訊',
        'info_character_length': '文字長度',
        'info_data_codeword_number': '資料字塊數',
        'info_error_correct_codeword_number': '修正字塊數',
        'info_encoding_mode': '資料類型',
        'info_error_correct_level': '錯誤修正等級',
        'info_mask_index': '遮罩編號',
        'info_penalty_score': '罰分',
        'info_version': '版本',
        'label_background_color': '背景顏色',
        'label_background_color_hex_hover': '背景顏色的 RGB 值',
        'label_background_hover': '勾選時有背景，若要透明請取消勾選',
        'label_background_rotation': '背景旋轉',
        'label_background_rounded': '圓角',
        'label_custom_mask': '遮罩',
        'label_custom_mask_hover': '不同遮罩會有不同罰分，都可產生符合標準的 QR code，罰分愈低則愈識別成功率愈高',
        'label_error_correct_level': '錯誤修正等級',
        'label_error_correct_level_hover': '百分比數字高的等級產生出來的 QR code，即使有污損等不完整，在掃描時仍然可以成功識別，但格子會較多',
        'label_finder_pattern_type': '定位樣式',
        'label_finder_pattern_type_hover': '左上、右上、左下，定位標記的樣式',
        'label_foreground_color': '格子顏色',
        'label_foreground_color_hex_hover': '格子顏色的 RGB 值',
        'label_logo': '上傳圖片',
        'label_logo_hover': '上傳圖片置於 QRcode 中央',
        'label_mini': '自動編碼',
        'label_mini_hover': '自動以能辨識的最小版本處理，若希望自行設定，請取消勾選',
        'label_module_style': '格點樣式',
        'label_padding': '邊距',
        'label_padding_hover': '標準建議邊距保留四個格子的空白，較容易辨識，但您也可以自訂',
        'label_rotation': '旋轉',
        'label_urlencode': '網址編碼',
        'label_urlencode_hover': '網頁路徑使用非英數字時，自動使用網址編碼以便瀏覽器載入，若要強制使用原來文字，請取消勾選',
        'label_version': '版本',
        'label_version_hover': '較高的版本產生出來的 QR code，即使有污損等不完整，在掃描時仍然可以成功識別，但格子會較多，在同樣面積下會顯得更密集，可能反而降低識別的成功率',
        'message': '請一定要使用行動裝置掃描過，確認成功率沒有問題再下載拿去使用。有任何問題、希望增加功能或協助翻譯，請 email 到 cyberlancer Gmail',
        'name': '繁體中文',
        'option_best_mask': '最佳',
        'option_finder_pattern_type': ['方形', '尖角圓角', '外圓角', '內外圓角'],
        'option_min_version': '最小',
        'option_module_style': ['方格', '圓', '點'],
        'option_rotation': ['不旋轉', '順時針 45 度', '逆時針 135 度'],
        'tab_list': ['編碼', '設計', '圖示']
    }
};